### ISSUE TITLE
Empty readme on latest version with README.tpl

### ISSUE THREAD

**Issue by fschutt** [livioribeiro/cargo-readme#15]
The generated readme is empty. The `{{readme}}` does not seem to work anymore.

```
cargo install cargo-readme
cargo readme
```

with a README.tpl of:

```
[![Build Status](https://travis-ci.org/fschutt/printpdf.svg?branch=master)](https://travis-ci.org/fschutt/printpdf)

{{readme}}
```

The generated file only contains the badge, not the actual readme content.

**Comment by livioribeiro** [comment]
Sorry I took too long to answer.

I could not reproduce the error. Can you show your doc strings?

**Comment by quodlibetor** [comment]
This is possibly fixed by #16 if you have a lib project @fschutt .

**Comment by fschutt** [comment]
The repository I discovered this on is here: https://github.com/fschutt/printpdf

I'll try again to re-generate the README. Currently I have to update the README and the lib.rs file seperately (because of this issue). I'll reinstall cargo-readme and see if it's gone.

**Comment by fschutt** [comment]
It still happens. 

```
$ cargo readme --version
cargo-readme v2.0.1

$ cargo readme
[![Build Status](https://travis-ci.org/fschutt/printpdf.svg?branch=master)](https://travis-ci.org/fschutt/printpdf)



```

That's it, the content of the [lib.rs file](https://github.com/fschutt/printpdf/blob/master/src/lib.rs) is not included. You can try it for yourself, if you clone the repo, do `cargo install cargo-readme` and just run it.

**Comment by livioribeiro** [comment]
After some investigation, I found out that https://github.com/fschutt/printpdf has both `lib.rs` and `main.rs`.

`cargo-readme` behavior changed on version 2.0 in that it now first looks for a `main.rs` and then for a `lib.rs`.

I based this decision on what I was doing with `cargo-readme` itself, since it is primarily used as an application rather then a library, it made sense to make the change in version 2.0.

I failed to communicate this change properly when version 2.0 launched, but I will update the documentation to show the order which entrypoint files are searched.

To solve the problem of the blank readme, you can add a parameter to `cargo-readme`:

    cargo readme -i src/lib.rs

**Comment by fschutt** [comment]
Ah. Wouldn't it make sense to look for the `doc=false` in the Cargo.toml?

Often times, I have a library that exposes the API, but also a binary that exposes a CLI to the library. 

On another note, I should remove the main.rs, it doesn't do anything useful.

**Comment by fschutt** [comment]
yeah, if you have a project that has both a main.rs and a lib.rs, cargo doesn't know which one to use when you run `cargo doc`. Hence the `doc = false`, you have to add it if you have both files (cargo won't compile otherwise).
