### ISSUE TITLE
Cargo.toml parsing expects path key when [lib] section is found.

### ISSUE THREAD

**Issue by mendelt** [livioribeiro/cargo-readme#32]
Thank you for making cargo readme available. While using it I found a small issue

I tried running cargo readme on a crate with proc macro's in it. It had this section in its cargo.toml
```
[lib]
proc-macro = true
```

This causes cargo readme to fail with the error "Error: missing field `path` for key `lib`"
First of all this error could be made clearer, where was this field missing? what file?
But when the path key is not found it should just use the default src/lib.rs
For now I can get around this by adding
```
path = "scr/lib.rs"
```
to Cargo.toml

**Comment by mendelt** [comment]
I created a puill request where lib or bin sections without a path will just default to src/main.rs or src/lib.rs. If that's ok with you I can add some tests for it. I also found some deprecated warnings that I fixed. I'll add a separate pull request for those.

**Comment by Charles-Johnson** [comment]
> ```
> path = "scr/lib.rs"
> ```

Should be `path = "src/lib.rs"`

**Comment by mendelt** [comment]
> Should be `path = "src/lib.rs"`

Thanks! I fixed it. I had to read the text 10 times though before I saw where I mistyped :-)

**Comment by cmrschwarz** [comment]
Any updates on this? Unfortunately still happening 5 years later :sweat_smile: .
